import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import arrow from "../../public/arrow.png";
import Image from "next/image";
import InverseDinamicFooter from "./ui/inverseFooter";
import Link from "next/link";
import Calendario from "./ui/calendar";
import Provider from "./_trpc/Provider";
import Header from "./ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let home = "/";
  let hrefCalendario = "/calendario";
  return (
    <html
      className="flex background w-full h-[99vh] flex-col overflow items-center justify-center bg-blue-900"
      lang="en"
    >
      <body className="flex w-full h-[100vh] flex-col overflow items-center justify-center">
        <Provider>
          <div className="flex min-h-[100vh] flex-col min-w-full items-center justify-between pb-[65px] md:pb-[0px]">
            <Header />
            {children}
            <InverseDinamicFooter />
          </div>
        </Provider>
      </body>
    </html>
  );
}
